### ISSUE TITLE
Function and shortcut keys are not working.

### ISSUE THREAD

**Issue by scientiac** [stepanzubkov/where-is-my-sddm-theme#12]
I tested them with `sddm-theme --test-mode --theme .` and when I tried to press `f1` for help it didn't show the help text.  I am running NixOS unstable with dependencies `sddm qt5.qtquickcontrols2 qt5.qtgraphicaleffects`.

**Comment by stepanzubkov** [comment]
try to test theme with `sddm-greeter --test-mode --theme .`. I always test my themes this way.

**Comment by scientiac** [comment]
Sorry, I mistyped it I did use `sddm-greeter --test-mode --theme .`, does it work on yours? 

I tried to modify your theme to my liking, and ended up making [this](https://github.com/scientiac/gruvbox-minimal-sddm), I changed how the shortcuts worked though.

**Comment by stepanzubkov** [comment]
Yes, It work on my computer. What qt version are you using? It may differ from my qt version.

Your theme is cool! :) May you add free software license (MIT License, for example) to your theme so me and other people can use this free (with 4 essential software freedoms)?

**Comment by scientiac** [comment]
Done😉 Thanks for the theme.

**Comment by stepanzubkov** [comment]
I use Qt 5.15 version (currently KDE Plasma Qt version). I think your qt version is a cause of problems (may be shortcuts is not working in qt6). I will test it on my KDE Neon system, that is using qt6.
