### ISSUE TITLE
Weird looking artifacts on cursor (AMDGPU?)

### ISSUE THREAD

**Issue by moritz1000** [stepanzubkov/where-is-my-sddm-theme#13]
Hello,

I get this weird looking artifacts on my cursor (see attachments) when using `where-is-my-sddm-theme`:
- I think it's worse when using a background image but it also happens when using the default black background
- `cursorColor: random` -> this changes a few pixels at the very top of the cursor but otherwise the cursor stays white
- `cursorColor: constantRandom/#<hex color>` -> does not really work as well

**On my NVIDIA GTX 1060 card I did not have any issue with `where-is-my-sddm-theme`.** 
They only appeared when I switched to an AMD 6700XT GPU a few days ago but I don't have issues with other SDDM themes!
___
I did reset all my `where-is-my-sddm-theme` settings and tried using the theme on a fresh installation of Arch Linux but got the same problem.

Any idea what might cause this issue and how I can fix this?
Kind regards.
___

![image](https://github.com/stepanzubkov/where-is-my-sddm-theme/assets/35174351/88ed4dc6-46a8-423e-b17a-e7b964073e67)
![image](https://github.com/stepanzubkov/where-is-my-sddm-theme/assets/35174351/79a89f73-9d0d-4407-b72c-b95f2da77a0d)
![image](https://github.com/stepanzubkov/where-is-my-sddm-theme/assets/35174351/a2785e78-433d-4c7b-b089-42c08fb54bcb)
![image](https://github.com/stepanzubkov/where-is-my-sddm-theme/assets/35174351/f6622d05-d860-4952-9926-6c8d0ceafe82)

**Comment by stepanzubkov** [comment]
Oh, I have no idea right now. I use Nvidia GPU and I haven't any bugs. I'll fix if I understand what's wrong with AMD gpus.

**Comment by rayzwastaken** [comment]
Same problem here, using completely AMD. Not super noticeable though.

**Comment by stepanzubkov** [comment]
@moritz1000 @rayzwastaken Please, test version from main branch and give feedback

**Comment by moritz1000** [comment]
@stepanzubkov @emgyrz Thank you so much, the issue is also fixed for me. I wonder how you managed to figure this one out?!

**Comment by emgyrz** [comment]
> I wonder how you managed to figure this one out?!

it was just luck :) 
I thought that the shadow is not so easy to render, then tried without it and the bug disappeared. but, actually, it's a bug of either Qt or amdgpu drivers, I think
