### ISSUE TITLE
option for font size?

### ISSUE THREAD

**Issue by PsyNyde** [stepanzubkov/where-is-my-sddm-theme#14]
I have a 1366x768 display where the password characters are huge and not fitting in the screen. although it isn't an unusable issue but font size option should help with aesthetics.

**Comment by stepanzubkov** [comment]
Of course, it should be added

**Comment by PsyNyde** [comment]
Looks like added with v1.6.0. haven't tested personally but should work.
so closing the issue.❤️

**Comment by W-Y-R** [comment]
Did you have the chance to try it out? It doesn't seem to work for me.

**Comment by PsyNyde** [comment]
> Did you have the chance to try it out? It doesn't seem to work for me.

are you sure you have the correct version?
i haven't tried myself cause sddm itself stopped working for me.

i reviewed the code though it should work without any issue

**Comment by W-Y-R** [comment]
I double-checked and it seems that the package manager still has the old version. The new version got merged a few days ago, but it still has not arrived in the channels yet. 

Will probably work when the new version arrives.

**Comment by PsyNyde** [comment]
> Will probably work when the new version arrives.
i presume you're using nix as you've mentioned about channels. if so you can just use a overlay to get the newest version.

**Comment by W-Y-R** [comment]
I could, yeah, but the version will probably hit the channels these days anyway, so there's no point in doing that.

However, I will write an update here when that happens.

**Comment by stepanzubkov** [comment]
Now I can't update package on pling.com, but you can install it manually using `install.sh` script.

**Comment by W-Y-R** [comment]
I just tested it and everything works fine.
