### ISSUE TITLE
Main.qml Error

### ISSUE THREAD

**Issue by timothfee** [stepanzubkov/where-is-my-sddm-theme#18]
Getting this error whenever trying to utilize the theme:

main.qml:2:1: plugin cannot be loaded for module "QtQuick.Controls": Cannot protect module QtQuick.Controls 2 as it was never registered

Any ideas?

**Comment by stepanzubkov** [comment]
What QT version do you use?

**Comment by timothfee** [comment]
I was attempting to install it on Ubuntu and I have since moved to Arch and it works perfectly. Thank you.

**Comment by timothfee** [comment]
Installed on Arch, works fine.
