### ISSUE TITLE
request for some features

### ISSUE THREAD

**Issue by Cherkah** [stepanzubkov/where-is-my-sddm-theme#23]
hi & thank for your work

1) what is the use to the option `type=image` in the `../theme.conf.user` s'  file ?
2) can it be possible to get the cursor blinking ?
3) can you provide a blur-effect for the background ? 

regards

**Comment by stepanzubkov** [comment]
1. It is probably kde auto-generated file with setting about image background
2. I think it is possible, but I did not see Qt Quick native features for this
3. I think I implement this feature in next release

**Comment by Cherkah** [comment]
@stepanzubkov 
> I think it is possible, but I did not see Qt Quick native features for this

 there are ton of topic about blinking cursor on the web. Maybe you'll find one of then that will fit the case
> ...I implement this feature in next release

it will be great if you can do it :)

regard

**Comment by stepanzubkov** [comment]
Cursor blinking done by #35
