### ISSUE TITLE
rejects my password 

### ISSUE THREAD

**Issue by miko180601** [stepanzubkov/where-is-my-sddm-theme#28]
for some reason it rejects my password.

I unmasked the characters so I am sure that the password is correct. 
I switched to breeze by editing kde_settings.conf and I can login without issues.

**Comment by stepanzubkov** [comment]
Do you use the latest version of the theme? Did you check user and session?

**Comment by joobert** [comment]
> for some reason it rejects my password.
> 
> 
> 
> I unmasked the characters so I am sure that the password is correct. 
> 
> I switched to breeze by editing kde_settings.conf and I can login without issues.

PLEASE tell me how you did this

**Comment by miko180601** [comment]
> > for some reason it rejects my password.
> > I unmasked the characters so I am sure that the password is correct.
> > I switched to breeze by editing kde_settings.conf and I can login without issues.
> 
> PLEASE tell me how you did this

for the 1st one is I changed the theme.conf in /usr/share/sddm/themes/where_is_my_sddm_theme_qt5

# Mask password characters or not ("true" or "false")
passwordMask=false

I swtiched to breeze by logging in to tty since I can't get to the desktop. I opened the kde_settings.conf in /etc

**Comment by miko180601** [comment]
> Do you use the latest version of the theme? Did you check user and session?

I installed the qt5 through the settings manager in plasma. I'm using plasma version 5.27.8, qt version 5.15.10 on kubuntu.

**Comment by stepanzubkov** [comment]
Fixed

**Comment by miko180601** [comment]
> Fixed

thank you so much!
