### ISSUE TITLE
Fix your code buddy

### ISSUE THREAD

**Issue by joobert** [stepanzubkov/where-is-my-sddm-theme#29]
Doesn't accept my correct password. You are irresponsible for releasing this.

**Comment by stepanzubkov** [comment]
Calm down. I am working on this problem.

**Comment by joobert** [comment]
> Calm down. I am working on this problem.

I was frustrated being locked out of my desktop. Very cool concept though man.

Would be nice to have the ability to disable the rainbow cursor.

**Comment by stepanzubkov** [comment]
@joobert You can change the color of cursor by setting `passwordCursorColor` in `theme.conf`. For example:
`passwordCursorColor=#ffffff` (for white cursor)

Also, if your current sddm theme is not working, you can switch to another TTY with `Alt+Ctrl+F2` (or another F-key), then change sddm current theme in sddm conf file (for me it's in `/etc/sddm.conf.d/kde_settings.conf`), then reboot and login normally.

**Comment by joobert** [comment]
> @joobert You can change the color of cursor by setting `passwordCursorColor` in `theme.conf`. For example: `passwordCursorColor=#ffffff` (for white cursor)
> 
> Also, if your current sddm theme is not working, you can switch to another TTY with `Alt+Ctrl+F2` (or another F-key), then change sddm current theme in sddm conf file (for me it's in `/etc/sddm.conf.d/kde_settings.conf`), then reboot and login normally.

Ahh I see all the config settings now, cool stuff. I guess I missed it when I came here in a rage, lol. Definitely gonna give this another shot, thanks for fixing.
