### ISSUE TITLE
Doesn't work on Qt6 (Plasma 6)

### ISSUE THREAD

**Issue by OddDev** [stepanzubkov/where-is-my-sddm-theme#31]
QtGraphicalEffects 1.0 was not shipped with Qt6: https://wiki.qt.io/Checklist_for_Qt_6.0_inclusion#Qt_Graphical_Effects

More information here: 
https://forum.qt.io/topic/121329/qtgraphicaleffects-not-available-in-qt6-qml/24

I'm not too sure what's the best fix here, but on my local qt6 it works when replacing the import with `import Qt5Compat.GraphicalEffects`.

**Comment by OddDev** [comment]
Sorry, it is only fixed in `sddm-greeter-qt6 --test-mode --theme /usr/share/sddm/themes/where_is_my_sddm_theme/`. The real login still shows a fallback.

**Comment by stepanzubkov** [comment]
I use qt6 theme and I haven't any errors. Check your sddm logs and send me please

**Comment by OddDev** [comment]
Ah sorry, fairly new to sddm things :)

I indeed found
`Mai 12 19:54:26 tuxedo sddm[766]: Loading theme configuration from "/usr/share/sddm/themes/where_is_my_sddm_theme/theme.conf"
Mai 12 19:54:26 tuxedo sddm[766]: The theme at "/usr/share/sddm/themes/where_is_my_sddm_theme" requires missing "/usr/bin/sddm-greeter" . Using fallback theme.` 🚀

Looking into how to solve this. But it, indeed, looks more like a "me" problem. :grin:

**Comment by OddDev** [comment]
Update: I have a greeter called `sddm-greeter-qt6` in `/usr/bin`

**Comment by OddDev** [comment]
Figured it out! I'm very sorry. It was totally on my end.
I upgraded my OS which included an update to Plasma 6 (TuxedoOS). Afterwards `where is my sddm` didn't work anymore. 

Now I just uninstalled the theme and installed it again, and it, indeed, offered me an option to install the `qt6` version! When I installed that one everything worked again. 

Thanks for the help @stepanzubkov !
