### ISSUE TITLE
Username passed to PAM is empty ("")

### ISSUE THREAD

**Issue by jalil-salame** [stepanzubkov/where-is-my-sddm-theme#33]
I just installed this theme but could not login, checking the journal I found out that the username was not being set:

```console
$ journalctl -xeu display-manager.service
...
Jun 09 12:54:51 libra sddm-helper[4896]: [PAM] Starting...
Jun 09 12:54:51 libra sddm-helper[4896]: [PAM] Authenticating...
Jun 09 12:54:51 libra sddm-helper[4896]: [PAM] Preparing to converse...
Jun 09 12:54:51 libra sddm-helper[4896]: [PAM] Conversation with 1 messages
Jun 09 12:54:51 libra sddm-helper[4896]: pam_unix(sddm:auth): check pass; user unknown
Jun 09 12:54:51 libra sddm-helper[4896]: pam_unix(sddm:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=
Jun 09 12:54:51 libra sddm-helper[4896]: pam_unix(sddm:auth): check pass; user unknown
Jun 09 12:54:53 libra sddm-helper[4896]: [PAM] authenticate: Authentication failure
Jun 09 12:54:53 libra sddm-helper[4896]: [PAM] returning.
Jun 09 12:54:53 libra sddm-helper[4896]: PAM 1 more authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=
Jun 09 12:54:53 libra sddm[2706]: Authentication error: SDDM::Auth::ERROR_AUTHENTICATION "Authentication failure"
Jun 09 12:54:53 libra sddm[2706]: Authentication for user  ""  failed
Jun 09 12:54:53 libra sddm-helper[4896]: [PAM] Asked to close the session but it wasn't previously open
Jun 09 12:54:53 libra sddm-helper[4896]: [PAM] Ended.
Jun 09 12:54:53 libra sddm[2706]: Auth: sddm-helper exited with 1
...
```

Switching to the default sddm theme fixes it.

**Comment by stepanzubkov** [comment]
Hmm, try to switch to where-is-my-sddm-theme again, maybe `userModel.lastIndex` was empty at the first time

**Comment by jalil-salame** [comment]
I'll try this tomorrow c:

**Comment by jalil-salame** [comment]
One issue I am seeing (unrelated to this) is `Could not convert "passwordInputWidth" (value QVariant(QString, "0.5") ) to int`. I think it happens here:

https://github.com/stepanzubkov/where-is-my-sddm-theme/blob/bdde61b875bcf7321d00b38049cb564250cb0a8c/where_is_my_sddm_theme/Main.qml#L216

It should be interpreted as a `double` or `float` (but I think QML has no floats(?)), but it is interpreted as an `int`.

It should not prevent me from logging in though.

**Comment by jalil-salame** [comment]
I don't know if switching to Qt6 or just rerunning it fixed it. But it works now c:

**Comment by stepanzubkov** [comment]
> One issue I am seeing (unrelated to this) is `Could not convert "passwordInputWidth" (value QVariant(QString, "0.5") ) to int`. I think it happens here:
> 
> https://github.com/stepanzubkov/where-is-my-sddm-theme/blob/bdde61b875bcf7321d00b38049cb564250cb0a8c/where_is_my_sddm_theme/Main.qml#L216
> 
> It should be interpreted as a `double` or `float` (but I think QML has no floats(?)), but it is interpreted as an `int`.
> 
> It should not prevent me from logging in though

Fixed in main branch
