### ISSUE TITLE
SDDM Users appears as black text 

### ISSUE THREAD

**Issue by Panonim** [stepanzubkov/where-is-my-sddm-theme#34]
So basically what it does is that users text does not appear and is just plain black instead I will try to fix that issue, but it's most likley to happen that I wont fix that.

**Comment by Panonim** [comment]
![obraz](https://github.com/stepanzubkov/where-is-my-sddm-theme/assets/58903942/e7bceb6b-f9a3-4a50-b6b7-eb746af3dc88)

**Comment by Panonim** [comment]
that is not a thing in nocursor 
![obraz](https://github.com/stepanzubkov/where-is-my-sddm-theme/assets/58903942/0384076c-c257-4a52-b5c8-07188ee92540)

**Comment by Panonim** [comment]
According to chatgpt there was only 2 changes in the files so I have no idea why this is a thing, because I tested bot of them
![obraz](https://github.com/stepanzubkov/where-is-my-sddm-theme/assets/58903942/323e6633-4617-4b2a-aa06-dcb7e4d5634f)

**Comment by Panonim** [comment]
I tested this with gray theme too and there is no such error

**Comment by stepanzubkov** [comment]
Maybe your user's real name is empty? So you should set `showUserRealNameByDefault=false` in `theme.conf`. With this flag theme will display your username instead of real name.

**Comment by Panonim** [comment]
Yeah, that was the issue, thanks for your anserw.
