### ISSUE TITLE
[feature request] add the ability to suspend, restart and poweroff?

### ISSUE THREAD

**Issue by name-snrl** [stepanzubkov/where-is-my-sddm-theme#6]
I'm not asking you to add buttons. I want to keep a minimalistic look. But it also seems strange to me that the only way to leave DM is to log in or switch to a tty where you also need to log in.

I suggest adding hotkeys for the functions I mentioned, eg. F10, F11, F12. And also make a tooltip where all the binds will be listed and a small hint on the main screen like `press F1 for help`.

**Comment by stepanzubkov** [comment]
Yes, I was thinking about help by `F1`, but I am not sure about `press F1 for help` hint. Anyway, I realize this soon
